### ISSUE TITLE
ginger wallet crashed

### ISSUE THREAD

**Issue by Combatresearch** [GingerPrivacy/GingerWallet#109]
Exception type: System.NotSupportedException

Message: Tor was started by another user and we can't use it nor kill it.

Stack Trace:    at WalletWasabi.Tor.TorProcessManager.RestartingLoopForBundledTorAsync(CancellationToken globalCancellationToken)
   at WalletWasabi.Daemon.Global.DisposeAsync()
   at WalletWasabi.Fluent.Desktop.WasabiAppExtensions.RunAsGuiAsync(WasabiApplication app)
   at WalletWasabi.Fluent.Desktop.Program.Main(String[] args)

Inner Exception: Exception type: WalletWasabi.Tor.Control.Exceptions.TorControlException

Message: Cookie file does not exist.

Stack Trace:    at WalletWasabi.Tor.TorProcessManager.InitTorControlAsync(CancellationToken token)
   at WalletWasabi.Tor.TorProcessManager.RestartingLoopForBundledTorAsync(CancellationToken globalCancellationToken)

Inner Exception:

**Comment by luzius1089** [comment]
# Ginger Troubleshooting Guide

## Restart and Simplify  
Restart your machine and start Ginger. This is the simplest solution, and it will work. 

## Reason  
If you run another software that starts the Tor process in the background (e.g., another Ginger instance or Wasabi), the current software won't be able to start the Tor process again because it is already running. This will result in the error message you encountered.

This issue may also occur if:  
1. You are using Windows with multiple user profiles and running different software in each profile.  
2. You are using Ginger and Wasabi simultaneously.  

## Solution for Parallel Usage  
While you can use both software, they cannot run simultaneously. To address this:  
1. Go to settings in both Ginger and Wasabi.  
2. Ensure neither software is set to start automatically with the system.  
3. In Ginger, navigate to **Settings > General** and enable **"Terminate Tor when Ginger shuts down."**

## Important Note  
By default, when you close the software, it will continue to run in the background. To shut down the software entirely:  
1. Go to the tray area, right-click on the Ginger icon, and select **"Quit."**  
2. Alternatively, you can disable this behavior by navigating to **Settings > General** and setting **"Run in background when windows closed"** to **Off.**
